import type { Competition } from "./types";

/** Hand-picked CN / agent / developer contests beyond AIGC feeds. */
export const CURATED_COMPETITIONS: Competition[] = [
  {
    id: "curated-tencent-hack-2026",
    title: "腾讯云黑客松 · 游戏开发挑战赛 2026",
    url: "https://tch.cloud.tencent.com/",
    summary:
      "腾讯云系列黑客松入口，含游戏开发、Agent 应用等主题赛道，面向全球高校开发者。",
    region: "cn",
    kind: "hackathon",
    status: "open",
    organizer: "腾讯云",
    prize: "最高约 ¥100 万（主题赛）",
    deadline: "2026-09-13",
    deadlineLabel: "约 9 月 13 日（以官网为准）",
    source: "腾讯云黑客松",
    tags: ["游戏", "Agent"],
    publishedAt: "2026-04-17T00:00:00.000Z",
  },
  {
    id: "curated-oaic-factory26",
    title: "OAIC 智能体软件工厂国际黑客松 2026",
    url: "https://create.gosim.org/factory26/",
    summary:
      "用 Agent 做真实软件工程：研习营 + 线上初赛，支持多条 Agent 工具路径，全球开放。",
    region: "global",
    kind: "agent",
    status: "open",
    organizer: "OAIC / 启悟社",
    deadline: "2026-09-30",
    deadlineLabel: "初赛约 9/21–9/30",
    source: "OAIC",
    tags: ["软件工程"],
    publishedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "curated-xfyun-2026",
    title: "iFLYTEK AI 开发者大赛 / 星火杯",
    url: "https://challenge.xfyun.cn/",
    summary: "科大讯飞官方竞赛平台：算法赛 + 智能体应用赛，星火杯面向高校学生。",
    region: "cn",
    kind: "application",
    status: "open",
    organizer: "科大讯飞",
    source: "讯飞挑战平台",
    tags: ["智能体", "大模型", "高校"],
    publishedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "curated-open-agent-2026",
    title: "Open Agent Hackathon 2026",
    url: "https://hackathon.genai.works/event/open-agent-hackathon-2026",
    summary:
      "纯线上 72 小时，做真正解决实际问题的 Agent；报名约 10/5 截止，构建窗口 10/7–9。",
    region: "online",
    kind: "agent",
    status: "upcoming",
    organizer: "GenAI.Works",
    prize: "最高约 $20,000",
    deadline: "2026-10-05",
    deadlineLabel: "报名至 10 月 5 日",
    source: "GenAI.Works",
    tags: ["Agent", "线上", "72h"],
    publishedAt: "2026-08-14T00:00:00.000Z",
  },
  {
    id: "curated-nebius-nvidia-2026",
    title: "Nebius × NVIDIA Global AI Hackathon",
    url: "https://nebiusglobalaihackathon.devpost.com/",
    summary:
      "用 NVIDIA 开源模型 + Nebius GPU 做可运行 AI 系统，含 Agent / Apps 等赛道。",
    region: "online",
    kind: "hackathon",
    status: "open",
    organizer: "Nebius / NVIDIA",
    prize: "约 $50,000",
    deadline: "2026-10-30",
    deadlineLabel: "截止约 10 月 30 日",
    source: "Devpost",
    tags: ["NVIDIA", "开源模型", "Agent"],
    publishedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "curated-since-ai-2026",
    title: "Since AI Hackathon 2026（芬兰图尔库）",
    url: "https://sinceai.ai/hackathon",
    summary:
      "MLH 成员赛事，72 小时、约 1000 名 builder、5 万欧元现金奖池，11 月 6–8 日。",
    region: "global",
    kind: "hackathon",
    status: "upcoming",
    organizer: "Since AI",
    prize: "€50,000",
    deadline: "2026-11-06",
    deadlineLabel: "活动 11 月 6–8 日",
    source: "Since AI",
    tags: ["MLH", "线下"],
    publishedAt: "2026-06-01T00:00:00.000Z",
  },
  {
    id: "curated-brics-agent-2026",
    title: "BRICS 2026 · AI 智能体与 VLA 具身智能等赛项",
    url: "https://www.bricsacademy.org.cn/",
    summary: "金砖相关技能/产业大赛平台，多个 AI 智能体、大模型应用赛项仍在报名窗口。",
    region: "cn",
    kind: "application",
    status: "open",
    organizer: "BRICS Academy",
    deadline: "2026-10-20",
    deadlineLabel: "部分赛项报至 10 月",
    source: "BRICS",
    tags: ["智能体", "具身智能"],
    publishedAt: "2026-04-30T00:00:00.000Z",
  },
  {
    id: "curated-huawei-c4-ai",
    title: "中国高校计算机大赛—人工智能创意赛（鸿蒙赛道）",
    url: "https://developer.huawei.com/consumer/cn/",
    summary: "国赛级 AI 创意赛，含鸿蒙 Agent / 应用创新赛道；关注官网等下一届报名。",
    region: "cn",
    kind: "application",
    status: "watch",
    organizer: "华为 / 高校计算机大赛",
    source: "华为开发者",
    tags: ["鸿蒙", "Agent", "国赛"],
    publishedAt: "2026-07-01T00:00:00.000Z",
  },
];
