import type { WatchSource } from "./types";

/** Platforms worth checking regularly for newly posted AI contests. */
export const WATCH_SOURCES: WatchSource[] = [
  {
    id: "aivs",
    name: "AI赛事雷达 aivs.one",
    url: "https://aivs.one/",
    cadence: "每天",
    focus: "可灵 / 即梦 / TapNow 等 AIGC 创作赛聚合（本站已接入其公开数据）",
    region: "cn",
  },
  {
    id: "devpost-ai",
    name: "Devpost · AI 专区",
    url: "https://devpost.com/c/artificial-intelligence",
    cadence: "每天",
    focus: "全球黑客松，更新最快",
    region: "global",
  },
  {
    id: "lablab",
    name: "lablab.ai",
    url: "https://lablab.ai/ai-hackathons",
    cadence: "每周 2–3 次",
    focus: "AI 黑客松专站，几乎周周有新赛",
    region: "online",
  },
  {
    id: "competehub",
    name: "CompeteHub",
    url: "https://competehub.dev/zh",
    cadence: "每周",
    focus: "中文 AI / 算法赛聚合",
    region: "cn",
  },
  {
    id: "tencent-hack",
    name: "腾讯云黑客松",
    url: "https://tch.cloud.tencent.com/",
    cadence: "每周",
    focus: "腾讯系列黑客松入口",
    region: "cn",
  },
  {
    id: "xfyun",
    name: "讯飞 AI 开发者大赛",
    url: "https://challenge.xfyun.cn/",
    cadence: "每周",
    focus: "算法 + 应用 / 智能体",
    region: "cn",
  },
  {
    id: "tianchi",
    name: "阿里天池",
    url: "https://tianchi.aliyun.com/competition",
    cadence: "每周",
    focus: "阿里系竞赛总入口",
    region: "cn",
  },
  {
    id: "kaggle",
    name: "Kaggle Competitions",
    url: "https://www.kaggle.com/competitions",
    cadence: "每周",
    focus: "算法 / 奖金赛，看 Active",
    region: "online",
  },
  {
    id: "volc",
    name: "火山引擎开发者活动",
    url: "https://developer.volcengine.com/activities",
    cadence: "每周",
    focus: "扣子 / 豆包相关挑战",
    region: "cn",
  },
  {
    id: "mlh",
    name: "MLH 赛事日历",
    url: "https://mlh.io/seasons/2026/events",
    cadence: "每周",
    focus: "Major League Hacking 官方赛历",
    region: "global",
  },
];
